### ISSUE TITLE
any recommendation on converting markdown to html/pdf with img and math?

### ISSUE THREAD

**Issue by xarthurx** [computational-robotics-lab/comp-fab-a1#3]
Hi, any recommendations on converting markdown file into pdf/html with img and math?

Tried several, either image is missing or math is not displayed properly...

**Comment by moritzge** [comment]
Hi, have at look at [Typora](https://typora.io/).

**Comment by xarthurx** [comment]
Hi, thanks.
I have no problem editing/viewing in vsCode. 
Just export for uploading.

If it is ok for you to export itself, I'm fine. :)
