### ISSUE TITLE
Quadratic Function

### ISSUE THREAD

**Issue by SimiPro** [computational-robotics-lab/comp-fab-a1#4]
So for me its a bit unclear about the quadratic function: $f(x) = x' a x + b'x + c$ since common in literature is that lower case letter stands either for vector or scalar but written in this way it seems to stand for a vector. But when a is a vector then f(x) is not really a function since b'x is a scalar and x'ax is a vector so im a bit confused. Can you maybe clarify that shortly ?

**Comment by moritzge** [comment]
If you look at the [code](https://github.com/computational-robotics-lab/comp-fab-a1/blob/b3c25031a132f1ba940ebe494902ce6a0a7f2f1a/src/app/main.cpp#L56): 
`return x2.dot(a.cwiseProduct(x2)) + b.dot(x2) + c;`

`a.cwiseProduct(x2)` multiplies the vectors a and x2 component-wise. Thus, it corresponds to the [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)). 

A more common way to write a quadratic function is using a Matrix A:
f(x) = x'Ax + ...
In our case, A is a diagonal matrix.

Either way, we end up with: f(x) = a1*x1^2 + a2*x^2 + b1*x1 + b2*x2 + c
(x = [x1, x2]', a = [a1, a2]', b = [b1, b2]')

I hope it is clear now.

**Comment by SimiPro** [comment]
Perfectly clear thanks alot!
