### ISSUE TITLE
Do we have to implement a step function for the Newton's method

### ISSUE THREAD

**Issue by yck011522** [computational-robotics-lab/comp-fab-a1#5]
The newton's method is using the variable step method by doing line search. 

This doesn't cause harm but it also doesn't make sense because SimplicialLDLT had already found the solution to the valley point of the Quadratic Approximation offered by the Hessian in the Newton's method. 

So maybe I should override the step function for the Newton's method?

**Comment by moritzge** [comment]
Newton's method is using line search on purpose. You are right, solving the linear system does find the minimum of the quadratic approximation. However, this step size might not be the optimal step size, if the actual function we are trying to minimize is not of quadratic form.

We can talk about it in more detail in the Q&A session on Friday.

**Comment by yck011522** [comment]
Thanks for the reply.
